version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
        - MYSQL_DATABASES=db
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_HOST=localhost
        - MYSQL_PORT=3306
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
